In [20]:
import pandas as pd
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

In [44]:
inventory = pd.read_csv('movie_inventory1.csv', engine = 'python')
meta = pd.read_csv('movie_meta.csv', engine = 'python')

inventory.drop('Unnamed: 0', axis = 1, inplace = True)

display(inventory)
display(meta)

,item_id,contract_year,movie_id,title,price,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,...,director,Genre_1,Genre_2,Genre_3,actor_1,actor_2,actor_3,contract_price,studio_score,price_class
0,I-1001,2015,tt0121766,Star Wars: Episode III - Revenge of the Sith,5500.0,2005,05-19-2005,140,PG-13,PG-13,...,George Lucas,Action,Adventure,Fantasy,Ewan McGregor,Natalie Portman,Hayden Christensen,2700,10,10
1,I-1002,2015,tt0330373,Harry Potter and the Goblet of Fire,4500.0,2005,11-18-2005,157,PG-13,PG-13,...,Mike Newell,Adventure,Family,Fantasy,Eric Sykes,Timothy Spall,David Tennant,2700,10,10
2,I-1003,2015,tt0363771,"The Chronicles of Narnia: The Lion, the Witc",5500.0,2005,12-09-2005,143,PG,PG,...,Andrew Adamson,Adventure,Family,Fantasy,Georgie Henley,Skandar Keynes,William Moseley,2295,10,1
3,I-1004,2015,tt0383574,Pirates of the Caribbean: Dead Man's Chest,5500.0,2006,07-07-2006,151,PG-13,PG-13,...,Gore Verbinski,Action,Adventure,Fantasy,Johnny Depp,Orlando Bloom,Keira Knightley,2295,10,1
4,I-1005,2015,tt0413300,Spider-Man 3,4000.0,2007,05-04-2007,139,PG-13,PG-13,...,Sam Raimi,Action,Adventure,Sci-Fi,Tobey Maguire,Kirsten Dunst,James Franco,2295,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,I-1102,2019,tt5095030,Ant-Man and the Wasp,7200.0,2018,07-06-2018,118,PG-13,PG-13,...,Peyton Reed,Action,Adventure,Comedy,Paul Rudd,Evangeline Lilly,Michael Pe��a,2295,10,1
102,I-1103,2019,tt4912910,Mission: Impossible - Fallout,5000.0,2018,07-27-2018,147,PG-13,PG-13,...,Christopher McQua,Action,Adventure,Thriller,Tom Cruise,Henry Cavill,Ving Rhames,2700,10,10
103,I-1104,2019,tt1727824,Bohemian Rhapsody,4500.0,2018,11-02-2018,134,PG-13,PG-13,...,Bryan Singer,Biography,Drama,Music,Rami Malek,Lucy Boynton,Gwilym Lee,2600,6,10
104,I-1105,2019,tt5848272,Ralph Breaks the Internet,7200.0,2018,11-21-2018,112,PG,PG,...,Phil Johnston,Animation,Adventure,Comedy,John C. Reilly,Sarah Silverman,Gal Gadot,2295,10,1
105,I-1106,2019,tt1477834,Aquaman,4500.0,2018,12-21-2018,143,PG-13,PG-13,...,James Wan,Action,Adventure,Fantasy,Jason Momoa,Amber Heard,Willem Dafoe,2295,10,1

,movie_id,title,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,imdb_score,votes,reviews_users,...,contract_price,studio_score,price_class,writer_1,writer_2,actor_1,actor_2,actor_3,description,storyline
0,tt0472033,9,2009,09-09-2009,79,PG-13,PG-13,7.1,127563,267,...,2195,6,1,Pamela Pettler,Shane Acker,Christopher Plummer,Martin Landau,John C. Reilly,A rag doll that awakens in a postapocalyptic f...,In a world destroyed in a war between man and ...
1,tt0478087,21,2008,03-28-2008,123,PG-13,PG-13,6.8,216963,302,...,2295,10,1,Peter Steinfeld,Allan Loeb,Jim Sturgess,Kevin Spacey,Kate Bosworth,"""21"" is the fact-based story about six MIT stu...","Ben Campbell is a young, highly intelligent, s..."
2,tt0453562,42,2013,04-12-2013,128,PG-13,PG-13,7.5,79204,234,...,2700,10,10,Brian Helgeland,NaN,Chadwick Boseman,Harrison Ford,Nicole Beharie,"In 1947, Jackie Robinson becomes the first Afr...","In 1946, Jackie Robinson is a Negro League bas..."
3,tt0416449,300,2006,03-09-2007,117,R,R,7.7,702777,2142,...,2700,10,10,Zack Snyder,Kurt Johnstad,Gerard Butler,Lena Headey,Dominic West,King Leonidas of Sparta and a force of 300 men...,In the Battle of Thermopylae of 480 BC an alli...
4,tt0450385,1408,2007,06-22-2007,104,PG-13,PG-13,6.8,245370,622,...,2145,4,1,Matt Greenberg,Scott Alexander,John Cusack,Tony Shalhoub,Len Cariou,A man who specialises in debunking paranormal ...,The cynical and skeptical writer Mike Enslin w...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1663,tt0443706,Zodiac,2007,03-02-2007,157,R,R,7.7,407046,698,...,2295,10,1,James Vanderbilt,Robert Graysmith,Jake Gyllenhaal,Mark Ruffalo,Anthony Edwards,"In the late 1960s/early 1970s, a San Francisco...",A serial killer in the San Francisco Bay Area ...
1664,tt1156398,Zombieland,2009,10-02-2009,88,R,R,7.6,482780,680,...,2600,6,10,Rhett Reese,Paul Wernick,Jesse Eisenberg,Woody Harrelson,Emma Stone,A shy student trying to reach his family in Oh...,Searching for family. In the early twenty-firs...
1665,tt1222817,Zookeeper,2011,07-08-2011,102,PG,PG,5.2,53731,132,...,2295,10,1,Nick Bakay,Rock Reuben,Kevin James,Rosario Dawson,Leslie Bibb,A group of zoo animals decide to break their c...,A group of zoo animals decide to break their c...
1666,tt1608290,Zoolander 2,2016,02-12-2016,101,PG-13,PG-13,4.7,61163,213,...,2295,10,1,Justin Theroux,Ben Stiller,Justin Bieber,Jon Daly,Pen��lope Cruz,Derek and Hansel are lured into modelling agai...,After many years of being separated from model...
1667,tt2948356,Zootopia,2016,03-04-2016,108,PG,PG,8.0,396148,642,...,2700,10,10,Byron Howard,Rich Moore,Ginnifer Goodwin,Jason Bateman,Idris Elba,"In a city of anthropomorphic animals, a rookie...",From the largest elephant to the smallest shre...

In [45]:
meta1 = meta[['movie_id', 'description']]
data = pd.merge(inventory, meta1, on = 'movie_id')
data

,item_id,contract_year,movie_id,title,price,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,...,Genre_1,Genre_2,Genre_3,actor_1,actor_2,actor_3,contract_price,studio_score,price_class,description
0,I-1001,2015,tt0121766,Star Wars: Episode III - Revenge of the Sith,5500.0,2005,05-19-2005,140,PG-13,PG-13,...,Action,Adventure,Fantasy,Ewan McGregor,Natalie Portman,Hayden Christensen,2700,10,10,"Three years into the Clone Wars, the Jedi resc..."
1,I-1002,2015,tt0330373,Harry Potter and the Goblet of Fire,4500.0,2005,11-18-2005,157,PG-13,PG-13,...,Adventure,Family,Fantasy,Eric Sykes,Timothy Spall,David Tennant,2700,10,10,Harry Potter (Daniel Radcliffe) finds himself ...
2,I-1003,2015,tt0363771,"The Chronicles of Narnia: The Lion, the Witc",5500.0,2005,12-09-2005,143,PG,PG,...,Adventure,Family,Fantasy,Georgie Henley,Skandar Keynes,William Moseley,2295,10,1,Four kids travel through a wardrobe to the lan...
3,I-1004,2015,tt0383574,Pirates of the Caribbean: Dead Man's Chest,5500.0,2006,07-07-2006,151,PG-13,PG-13,...,Action,Adventure,Fantasy,Johnny Depp,Orlando Bloom,Keira Knightley,2295,10,1,Jack Sparrow races to recover the heart of Dav...
4,I-1005,2015,tt0413300,Spider-Man 3,4000.0,2007,05-04-2007,139,PG-13,PG-13,...,Action,Adventure,Sci-Fi,Tobey Maguire,Kirsten Dunst,James Franco,2295,10,1,A strange black entity from another world bond...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,I-1102,2019,tt5095030,Ant-Man and the Wasp,7200.0,2018,07-06-2018,118,PG-13,PG-13,...,Action,Adventure,Comedy,Paul Rudd,Evangeline Lilly,Michael Pe��a,2295,10,1,As Scott Lang balances being both a superhero ...
102,I-1103,2019,tt4912910,Mission: Impossible - Fallout,5000.0,2018,07-27-2018,147,PG-13,PG-13,...,Action,Adventure,Thriller,Tom Cruise,Henry Cavill,Ving Rhames,2700,10,10,"Ethan Hunt and his IMF team, along with some f..."
103,I-1104,2019,tt1727824,Bohemian Rhapsody,4500.0,2018,11-02-2018,134,PG-13,PG-13,...,Biography,Drama,Music,Rami Malek,Lucy Boynton,Gwilym Lee,2600,6,10,The story of the legendary British rock band Q...
104,I-1105,2019,tt5848272,Ralph Breaks the Internet,7200.0,2018,11-21-2018,112,PG,PG,...,Animation,Adventure,Comedy,John C. Reilly,Sarah Silverman,Gal Gadot,2295,10,1,"Six years after the events of ""Wreck-It Ralph,..."
105,I-1106,2019,tt1477834,Aquaman,4500.0,2018,12-21-2018,143,PG-13,PG-13,...,Action,Adventure,Fantasy,Jason Momoa,Amber Heard,Willem Dafoe,2295,10,1,"Arthur Curry (Jason Momoa), the human-born hei..."

In [48]:
director_list = list(data['director'])
actor_list = list(data['actor_1'])
genre_list = list(data['Genre_1'])
soup_list = []

for i in range(len(director_list)):
    soup = director_list[i].replace(" ", "") + str(" ") + \
    actor_list[i].replace(" ", "") + str(" ") + genre_list[i]
    soup_list.append(soup)

soup_list

['GeorgeLucas EwanMcGregor Action',
 'MikeNewell EricSykes Adventure',
 'AndrewAdamson GeorgieHenley Adventure',
 'GoreVerbinski JohnnyDepp Action',
 'SamRaimi TobeyMaguire Action',
 'ChrisMiller MikeMyers Animation',
 'GoreVerbinski JohnnyDepp Action',
 'MichaelBay ShiaLaBeouf Action',
 'DavidYates DanielRadcliffe Action',
 'FrancisLawrence WillSmith Adventure',
 'JonFavreau RobertDowneyJr. Action',
 'StevenSpielberg HarrisonFord Action',
 'ChristopherNolan ChristianBale Action',
 'J.J.Abrams ChrisPine Action',
 'PeteDocter EdwardAsner Animation',
 'ToddPhillips BradleyCooper Comedy',
 'MichaelBay ShiaLaBeouf Action',
 'DavidYates DanielRadcliffe Action',
 'JohnLeeHancock SandraBullock Biography',
 'ChrisWeitz KristenStewart Adventure',
 'JamesCameron SamWorthington Action',
 'JonFavreau RobertDowneyJr. Action',
 'LeeUnkrich TomHanks Animation',
 'DavidSlade XavierSamuel Adventure',
 'PierreCoffin SteveCarell Animation',
 'ChristopherNolan LeonardoDiCaprio Action',
 'ToddPhillips BradleyCooper Comedy',
 'MichaelBay ShiaLaBeouf Action',
 'GaryRoss StanleyTucci Action',
 'MarcWebb AndrewGarfield Action',
 'ChristopherNolan ChristianBale Action',
 'SamMendes DanielCraig Action',
 'PeterJackson IanMcKellen Adventure',
 'ZackSnyder HenryCavill Action',
 'DanScanlon BillyCrystal Animation',
 'PierreCoffin SteveCarell Animation',
 'AlfonsoCuarn SandraBullock Drama',
 'FrancisLawrence JenniferLawrence Action',
 'ChrisBuck KristenBell Animation',
 'PeterJackson IanMcKellen Adventure',
 'AnthonyRusso ChrisEvans Action',
 'JamesGunn ChrisPratt Action',
 'FrancisLawrence JenniferLawrence Action',
 'PeterJackson IanMcKellen Adventure',
 'ClintEastwood BradleyCooper Action',
 'PaulTibbitt AntonioBanderas Animation',
 'SamTaylor-Johnso DakotaJohnson Drama',
 'JossWhedon RobertDowneyJr. Action',
 'GeorgeMiller TomHardy Action',
 'ElizabethBanks AnnaKendrick Comedy',
 'BradPeyton DwayneJohnson Action',
 'PaulFeig JudeLaw Action',
 'ColinTrevorrow ChrisPratt Action',
 'PeteDocter AmyPoehler Animation',
 'KyleBalda SandraBullock Animation',
 'PeytonReed PaulRudd Action',
 'JuddApatow ColinQuinn Comedy',
 'ChristopherMcQua TomCruise Action',
 "F.GaryGray O'SheaJacksonJr. Biography",
 'GenndyTartakovsk AdamSandler Animation',
 'RidleyScott MattDamon Adventure',
 'SamMendes DanielCraig Action',
 'SteveMartino TromboneShorty Animation',
 'FrancisLawrence JenniferLawrence Action',
 'PeterSohn JeffreyWright Animation',
 'SeanAnders WillFerrell Comedy',
 'AlejandroG.I LeonardoDiCaprio Action',
 'TimMiller RyanReynolds Action',
 'ByronHoward GinniferGoodwin Animation',
 'ZackSnyder BenAffleck Action',
 'AnthonyRusso ChrisEvans Action',
 'BryanSinger JamesMcAvoy Action',
 'AndrewStanton EllenDeGeneres Animation',
 'ChrisRenaud LouisC.K. Animation',
 'JustinLin ChrisPine Action',
 'PaulGreengrass MattDamon Action',
 'DavidAyer WillSmith Action',
 'ScottDerrickson BenedictCumberbatch Action',
 'MikeMitchell AnnaKendrick Animation',
 "RonClements Auli'iCravalho Animation",
 'GarthJennings MatthewMcConaughey Animation',
 'TheodoreMelfi TarajiP.Henson Biography',
 'JordanPeele DanielKaluuya Horror',
 'F.GaryGray VinDiesel Action',
 'JamesGunn ChrisPratt Action',
 'PattyJenkins GalGadot Action',
 'KyleBalda SteveCarell Animation',
 'JonWatts TomHolland Action',
 'ChristopherNolan FionnWhitehead Action',
 'AndyMuschietti JaedenMartell Horror',
 'TaikaWaititi ChrisHemsworth Action',
 'ZackSnyder BenAffleck Action',
 'LeeUnkrich AnthonyGonzalez Animation',
 'JakeKasdan DwayneJohnson Action',
 'RyanCoogler ChadwickBoseman Action',
 'JohnKrasinski EmilyBlunt Drama',
 'AnthonyRusso RobertDowneyJr. Action',
 'DavidLeitch RyanReynolds Action',
 'RonHoward AldenEhrenreich Action',
 'BradBird CraigT.Nelson Animation',
 'J.A.Bayona ChrisPratt Action',
 'PeytonReed PaulRudd Action',
 'ChristopherMcQua TomCruise Action',
 'BryanSinger RamiMalek Biography',
 'PhilJohnston JohnC.Reilly Animation',
 'JamesWan JasonMomoa Action']

In [49]:
data['soup'] = soup_list
data.head()

,item_id,contract_year,movie_id,title,price,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,...,Genre_2,Genre_3,actor_1,actor_2,actor_3,contract_price,studio_score,price_class,description,soup
0,I-1001,2015,tt0121766,Star Wars: Episode III - Revenge of the Sith,5500.0,2005,05-19-2005,140,PG-13,PG-13,...,Adventure,Fantasy,Ewan McGregor,Natalie Portman,Hayden Christensen,2700,10,10,"Three years into the Clone Wars, the Jedi resc...",GeorgeLucas EwanMcGregor Action
1,I-1002,2015,tt0330373,Harry Potter and the Goblet of Fire,4500.0,2005,11-18-2005,157,PG-13,PG-13,...,Family,Fantasy,Eric Sykes,Timothy Spall,David Tennant,2700,10,10,Harry Potter (Daniel Radcliffe) finds himself ...,MikeNewell EricSykes Adventure
2,I-1003,2015,tt0363771,"The Chronicles of Narnia: The Lion, the Witc",5500.0,2005,12-09-2005,143,PG,PG,...,Family,Fantasy,Georgie Henley,Skandar Keynes,William Moseley,2295,10,1,Four kids travel through a wardrobe to the lan...,AndrewAdamson GeorgieHenley Adventure
3,I-1004,2015,tt0383574,Pirates of the Caribbean: Dead Man's Chest,5500.0,2006,07-07-2006,151,PG-13,PG-13,...,Adventure,Fantasy,Johnny Depp,Orlando Bloom,Keira Knightley,2295,10,1,Jack Sparrow races to recover the heart of Dav...,GoreVerbinski JohnnyDepp Action
4,I-1005,2015,tt0413300,Spider-Man 3,4000.0,2007,05-04-2007,139,PG-13,PG-13,...,Adventure,Sci-Fi,Tobey Maguire,Kirsten Dunst,James Franco,2295,10,1,A strange black entity from another world bond...,SamRaimi TobeyMaguire Action

In [50]:
count = CountVectorizer(analyzer='word', ngram_range=(1, 2), min_df=0,
                       stop_words='english')
count_matrix = count.fit_transform(data['soup'])

In [61]:
print(count.vocabulary_)

{'georgelucas': 140, 'ewanmcgregor': 122, 'action': 2, 'georgelucas ewanmcgregor': 141, 'ewanmcgregor action': 123, 'mikenewell': 230, 'ericsykes': 120, 'adventure': 5, 'mikenewell ericsykes': 231, 'ericsykes adventure': 121, 'andrewadamson': 14, 'georgiehenley': 144, 'andrewadamson georgiehenley': 15, 'georgiehenley adventure': 145, 'goreverbinski': 148, 'johnnydepp': 185, 'goreverbinski johnnydepp': 149, 'johnnydepp action': 186, 'samraimi': 275, 'tobeymaguire': 309, 'samraimi tobeymaguire': 276, 'tobeymaguire action': 310, 'chrismiller': 64, 'mikemyers': 228, 'animation': 22, 'chrismiller mikemyers': 65, 'mikemyers animation': 229, 'michaelbay': 224, 'shialabeouf': 291, 'michaelbay shialabeouf': 225, 'shialabeouf action': 292, 'davidyates': 107, 'danielradcliffe': 97, 'davidyates danielradcliffe': 108, 'danielradcliffe action': 98, 'francislawrence': 126, 'willsmith': 327, 'francislawrence willsmith': 128, 'willsmith adventure': 329, 'jonfavreau': 189, 'robertdowneyjr': 263, 'jonfavreau robertdowneyjr': 190, 'robertdowneyjr action': 264, 'stevenspielberg': 299, 'harrisonford': 150, 'stevenspielberg harrisonford': 300, 'harrisonford action': 151, 'christophernolan': 76, 'christianbale': 72, 'christophernolan christianbale': 77, 'christianbale action': 73, 'abrams': 0, 'chrispine': 66, 'abrams chrispine': 1, 'chrispine action': 67, 'petedocter': 244, 'edwardasner': 112, 'petedocter edwardasner': 246, 'edwardasner animation': 113, 'toddphillips': 311, 'bradleycooper': 46, 'comedy': 88, 'toddphillips bradleycooper': 312, 'bradleycooper comedy': 48, 'johnleehancock': 183, 'sandrabullock': 281, 'biography': 43, 'johnleehancock sandrabullock': 184, 'sandrabullock biography': 283, 'chrisweitz': 80, 'kristenstewart': 205, 'chrisweitz kristenstewart': 81, 'kristenstewart adventure': 206, 'jamescameron': 165, 'samworthington': 279, 'jamescameron samworthington': 166, 'samworthington action': 280, 'leeunkrich': 210, 'tomhanks': 315, 'leeunkrich tomhanks': 212, 'tomhanks animation': 316, 'davidslade': 105, 'xaviersamuel': 330, 'davidslade xaviersamuel': 106, 'xaviersamuel adventure': 331, 'pierrecoffin': 255, 'stevecarell': 295, 'pierrecoffin stevecarell': 256, 'stevecarell animation': 296, 'leonardodicaprio': 213, 'christophernolan leonardodicaprio': 79, 'leonardodicaprio action': 214, 'garyross': 136, 'stanleytucci': 293, 'garyross stanleytucci': 137, 'stanleytucci action': 294, 'marcwebb': 217, 'andrewgarfield': 16, 'marcwebb andrewgarfield': 218, 'andrewgarfield action': 17, 'sammendes': 273, 'danielcraig': 93, 'sammendes danielcraig': 274, 'danielcraig action': 94, 'peterjackson': 247, 'ianmckellen': 157, 'peterjackson ianmckellen': 248, 'ianmckellen adventure': 158, 'zacksnyder': 332, 'henrycavill': 152, 'zacksnyder henrycavill': 334, 'henrycavill action': 153, 'danscanlon': 99, 'billycrystal': 41, 'danscanlon billycrystal': 100, 'billycrystal animation': 42, 'alfonsocuarn': 10, 'drama': 109, 'alfonsocuarn sandrabullock': 11, 'sandrabullock drama': 284, 'jenniferlawrence': 177, 'francislawrence jenniferlawrence': 127, 'jenniferlawrence action': 178, 'chrisbuck': 58, 'kristenbell': 203, 'chrisbuck kristenbell': 59, 'kristenbell animation': 204, 'anthonyrusso': 28, 'chrisevans': 60, 'anthonyrusso chrisevans': 29, 'chrisevans action': 61, 'jamesgunn': 167, 'chrispratt': 68, 'jamesgunn chrispratt': 168, 'chrispratt action': 69, 'clinteastwood': 82, 'clinteastwood bradleycooper': 83, 'bradleycooper action': 47, 'paultibbitt': 242, 'antoniobanderas': 31, 'paultibbitt antoniobanderas': 243, 'antoniobanderas animation': 32, 'samtaylor': 277, 'johnso': 187, 'dakotajohnson': 91, 'samtaylor johnso': 278, 'johnso dakotajohnson': 188, 'dakotajohnson drama': 92, 'josswhedon': 195, 'josswhedon robertdowneyjr': 196, 'georgemiller': 142, 'tomhardy': 317, 'georgemiller tomhardy': 143, 'tomhardy action': 318, 'elizabethbanks': 114, 'annakendrick': 23, 'elizabethbanks annakendrick': 115, 'annakendrick comedy': 25, 'bradpeyton': 49, 'dwaynejohnson': 110, 'bradpeyton dwaynejohnson': 50, 'dwaynejohnson action': 111, 'paulfeig': 236, 'judelaw': 199, 'paulfeig judelaw': 237, 'judelaw action': 200, 'colintrevorrow': 86, 'colintrevorrow chrispratt': 87, 'amypoehler': 12, 'petedocter amypoehler': 245, 'amypoehler animation': 13, 'kylebalda': 207, 'kylebalda sandrabullock': 208, 'sandrabullock animation': 282, 'peytonreed': 251, 'paulrudd': 240, 'peytonreed paulrudd': 252, 'paulrudd action': 241, 'juddapatow': 197, 'colinquinn': 84, 'juddapatow colinquinn': 198, 'colinquinn comedy': 85, 'christophermcqua': 74, 'tomcruise': 313, 'christophermcqua tomcruise': 75, 'tomcruise action': 314, 'garygray': 133, 'sheajacksonjr': 289, 'garygray sheajacksonjr': 134, 'sheajacksonjr biography': 290, 'genndytartakovsk': 138, 'adamsandler': 3, 'genndytartakovsk adamsandler': 139, 'adamsandler animation': 4, 'ridleyscott': 261, 'mattdamon': 219, 'ridleyscott mattdamon': 262, 'mattdamon adventure': 221, 'stevemartino': 297, 'tromboneshorty': 321, 'stevemartino tromboneshorty': 298, 'tromboneshorty animation': 322, 'petersohn': 249, 'jeffreywright': 175, 'petersohn jeffreywright': 250, 'jeffreywright animation': 176, 'seananders': 287, 'willferrell': 325, 'seananders willferrell': 288, 'willferrell comedy': 326, 'alejandrog': 8, 'alejandrog leonardodicaprio': 9, 'timmiller': 307, 'ryanreynolds': 271, 'timmiller ryanreynolds': 308, 'ryanreynolds action': 272, 'byronhoward': 54, 'ginnifergoodwin': 146, 'byronhoward ginnifergoodwin': 55, 'ginnifergoodwin animation': 147, 'benaffleck': 37, 'zacksnyder benaffleck': 333, 'benaffleck action': 38, 'bryansinger': 51, 'jamesmcavoy': 169, 'bryansinger jamesmcavoy': 52, 'jamesmcavoy action': 170, 'andrewstanton': 18, 'ellendegeneres': 116, 'andrewstanton ellendegeneres': 19, 'ellendegeneres animation': 117, 'chrisrenaud': 70, 'louisc': 215, 'chrisrenaud louisc': 71, 'louisc animation': 216, 'justinlin': 201, 'justinlin chrispine': 202, 'paulgreengrass': 238, 'paulgreengrass mattdamon': 239, 'mattdamon action': 220, 'davidayer': 101, 'davidayer willsmith': 102, 'willsmith action': 328, 'scottderrickson': 285, 'benedictcumberbatch': 39, 'scottderrickson benedictcumberbatch': 286, 'benedictcumberbatch action': 40, 'mikemitchell': 226, 'mikemitchell annakendrick': 227, 'annakendrick animation': 24, 'ronclements': 265, 'auli': 33, 'icravalho': 159, 'ronclements auli': 266, 'auli icravalho': 34, 'icravalho animation': 160, 'garthjennings': 131, 'matthewmcconaughey': 222, 'garthjennings matthewmcconaughey': 132, 'matthewmcconaughey animation': 223, 'theodoremelfi': 305, 'tarajip': 303, 'henson': 154, 'theodoremelfi tarajip': 306, 'tarajip henson': 304, 'henson biography': 155, 'jordanpeele': 193, 'danielkaluuya': 95, 'horror': 156, 'jordanpeele danielkaluuya': 194, 'danielkaluuya horror': 96, 'vindiesel': 323, 'garygray vindiesel': 135, 'vindiesel action': 324, 'pattyjenkins': 234, 'galgadot': 129, 'pattyjenkins galgadot': 235, 'galgadot action': 130, 'kylebalda stevecarell': 209, 'jonwatts': 191, 'tomholland': 319, 'jonwatts tomholland': 192, 'tomholland action': 320, 'fionnwhitehead': 124, 'christophernolan fionnwhitehead': 78, 'fionnwhitehead action': 125, 'andymuschietti': 20, 'jaedenmartell': 161, 'andymuschietti jaedenmartell': 21, 'jaedenmartell horror': 162, 'taikawaititi': 301, 'chrishemsworth': 62, 'taikawaititi chrishemsworth': 302, 'chrishemsworth action': 63, 'anthonygonzalez': 26, 'leeunkrich anthonygonzalez': 211, 'anthonygonzalez animation': 27, 'jakekasdan': 163, 'jakekasdan dwaynejohnson': 164, 'ryancoogler': 269, 'chadwickboseman': 56, 'ryancoogler chadwickboseman': 270, 'chadwickboseman action': 57, 'johnkrasinski': 181, 'emilyblunt': 118, 'johnkrasinski emilyblunt': 182, 'emilyblunt drama': 119, 'anthonyrusso robertdowneyjr': 30, 'davidleitch': 103, 'davidleitch ryanreynolds': 104, 'ronhoward': 267, 'aldenehrenreich': 6, 'ronhoward aldenehrenreich': 268, 'aldenehrenreich action': 7, 'bradbird': 44, 'craigt': 89, 'nelson': 232, 'bradbird craigt': 45, 'craigt nelson': 90, 'nelson animation': 233, 'bayona': 35, 'bayona chrispratt': 36, 'ramimalek': 257, 'bryansinger ramimalek': 53, 'ramimalek biography': 258, 'philjohnston': 253, 'johnc': 179, 'reilly': 259, 'philjohnston johnc': 254, 'johnc reilly': 180, 'reilly animation': 260, 'jameswan': 171, 'jasonmomoa': 173, 'jameswan jasonmomoa': 172, 'jasonmomoa action': 174}

In [51]:
cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [58]:
print(cosine_sim)

[[1.  0.  0.  ... 0.  0.  0.2]
 [0.  1.  0.2 ... 0.  0.  0. ]
 [0.  0.2 1.  ... 0.  0.  0. ]
 ...
 [0.  0.  0.  ... 1.  0.  0. ]
 [0.  0.  0.  ... 0.  1.  0. ]
 [0.2 0.  0.  ... 0.  0.  1. ]]

In [52]:
titles = data['title']
indices = pd.Series(data.index, index = data['title'])

In [53]:
def getrecommandations(title):
    index = indices[title]
    sim_scores = list(enumerate(cosine_sim[index]))
    sim_scores = sorted(sim_scores, key=lambda x:x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores] 
    return titles.iloc[movie_indices]

In [54]:
getrecommandations('Harry Potter and the Goblet of Fire')

2     The Chronicles of Narnia: The Lion, the Witc
9                                      I Am Legend
19                     The Twilight Saga: New Moon
23                      The Twilight Saga: Eclipse
32               The Hobbit: An Unexpected Journey
39             The Hobbit: The Desolation of Smaug
43       The Hobbit: The Battle of the Five Armies
60                                     The Martian
0     Star Wars: Episode III - Revenge of the Sith
3       Pirates of the Caribbean: Dead Man's Chest
4                                     Spider-Man 3
5                                  Shrek the Third
6         Pirates of the Caribbean: At World's End
7                                     Transformers
8        Harry Potter and the Order of the Phoenix
10                                        Iron Man
11    Indiana Jones and the Kingdom of the Crystal
12                                 The Dark Knight
13                                       Star Trek
14                                              Up
15                                    The Hangover
16             Transformers: Revenge of the Fallen
17          Harry Potter and the Half-Blood Prince
18                                  The Blind Side
20                                          Avatar
21                                      Iron Man 2
22                                     Toy Story 3
24                                   Despicable Me
25                                       Inception
26                            The Hangover Part II
Name: title, dtype: object

In [57]:
data.groupby('actor_1').count()

,item_id,contract_year,movie_id,title,price,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,...,Genre_1,Genre_2,Genre_3,actor_2,actor_3,contract_price,studio_score,price_class,description,soup
actor_1,,,,,,,,,,,,,,,,,,,,,
Adam Sandler,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Alden Ehrenreich,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Amy Poehler,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Andrew Garfield,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Anna Kendrick,2,2,2,2,2,2,2,2,2,2,...,2,2,1,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Trombone Shorty,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Vin Diesel,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Will Ferrell,1,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
Will Smith,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Xavier Samuel,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1